### PR TITLE
Add pod annotations to Helm chart

### PR DESCRIPTION
**Pull request by roeizavida**
This PR adds an option to set pod annotations when using the Helm chart.

### CODE REVIEW

**Comment by martin-helmich** [comment]
LGTM :+1: -- Thanks for your contribution and sorry about the delay.

**Comment by roeizavida** [comment]
@martin-helmich Thanks. The workflow is not running so I wonder if there is something else I need to do.

**Comment by day1118** [comment]
@roeizavida 
I have created https://github.com/mittwald/kubernetes-secret-generator/pull/83 which allows templating the annotations. Would this also meet your needs?

**Comment by roeizavida** [comment]
> @roeizavida I have created #83 which allows templating the annotations. Would this also meet your needs?

@day1118 Yes, thanks.

**Pull request closed without merging**
